### ISSUE TITLE
Adding Books

### ISSUE THREAD

**Issue by rahulguptagamedev** [ch3nkula/programming-books-and-resources#17]
I got over 200 Gigs of books on various subject important matters such data compression, data mining, compiler design, data structures, python, C++ etc but I need time cause they in a semi sorted state so will be creating loads of pull requests.I was also looking for something like this, an online books resource for developers.

**Also can put the pull requests under Hacktoberfest?**

**Comment by xSavitar** [comment]
200GB of books is really huge. I don't think I can manage up to that capacity. Just select the top most 1 for each programming language and put in the respective directory, then make a PR and I will add hacktoberfest to it and merge. Does that make sense?

**Comment by rahulguptagamedev** [comment]
I got no problems with that also i think you should add  a folder for C#,ruby and .NET

**Comment by xSavitar** [comment]
Yes, you have a point. You can do that and make a PR with the books and I will merge. Note, just the best books in the folders not the 200GB :), we are trying to get the most recommended books. Thanks 👍

**Comment by xSavitar** [comment]
So we need both light weighted books and good content as well 👍
