### ISSUE TITLE
Free and paid books

### ISSUE THREAD

**Issue by wadleo** [ch3nkula/programming-books-and-resources#4]
Can you ensure no paid books are listed here for download, cause this might lead to proprietary claims against you. For example, [Thomas_H._Cormen,_Charles_E._Leiserson,_Ronald_L.(BookFi.org).pdf for algorithms is paid book, thanks.

**Comment by xSavitar** [comment]
I get your point @wadleo. There is a free version of that book and if you do a Google search, you will notice you can find a PDF version of the book online. Its not like I am saying in the repo I own the books. In fact, we need to make sure that we create a README.md file that focuses on the aspect that the books are free from online and is not our property. I don't know if you understand my point?

**Comment by wadleo** [comment]
:+1:  @ch3nkula
