### ISSUE TITLE
Add more Python programming recommended books

### ISSUE THREAD

**Issue by xSavitar** [ch3nkula/programming-books-and-resources#9]
This tasks requires that Python recommended books should be added to the repo under the Python folder.

**Comment by ghost** [comment]
I'll claim this one :D

**Comment by xSavitar** [comment]
Free free to do so and make sure to star the repo :D. Also, try as much as possible to send recommended books.

**Comment by ghost** [comment]
Is it limited to beginner books or can reach into more technical books as well?

**Comment by xSavitar** [comment]
It should cut across all the different levels. Creating a sub-directory tree inside Python like;
Python-|
              |- Beginner
              |- Intermediate
              |- Advanced
Will be good or also just putting all the books inside the Python directory is also good. Which ever is acceptable if you can differentiate the different levels of the books. There is no limitation :)
